packages:
  - packages/*
  - examples/*
  - website
  - tests
  - tests/integration/*

catalog:
  vitest: ^4.0.0
  '@vitest/coverage-v8': ^4.0.0
  typescript: ^5.0.0
  sass: ^1.70.0
  sass-loader: ^13.2.0
  "@types/node": "^20.19.0"

catalogs:
  example:
    '@ice/jsx-runtime': ^0.3.0
    '@swc/helpers': ^0.5.15
