packages:
  - packages/*
  - examples/*
  - website
  - packages/pkg/tests/fixtures/*

catalog:
  vitest: ^0.28.5
  '@vitest/coverage-c8': ^0.28.5
  typescript: ^4.9.4
  sass: ^1.58.3
  sass-loader: ^13.2.0
