export default {
  targetDir: 'Target dirname to generate',
  version: '@ice/create-pkg version: ',
  dirExistFiles: 'Files exist in the current directory already. Are you sure to continue ?',
  initSuccess: 'Initialize project successfully.',
  selectNpmScope: 'Please select npm scope',
  packageName: 'Package name',
  packageNameValidateError: (name: string) => `npm package name ${name} not validate, please retry`,
  selectProjectType: 'Please select project type',
  webLibrary: 'Web Library',
  nodeModule: 'Node Module',
  reactComponent: 'React Component',
  raxComponent: 'Rax Component',
  reactMonorepo: 'Monorepo React Components',
  nodeMonorepo: 'Monorepo Node Libs',
};
