export default {
  targetDir: '指定目录名以初始化项目',
  version: '@ice/create-pkg 版本： ',
  dirExistFiles: '当前目录已存在文件，是否继续？',
  initSuccess: '项目初始化成功',
  generateIntranetComponent: '生成仅内网可用的包',
  selectNpmScope: '请选择 npm scope',
  packageName: '包名',
  packageNameValidateError: (name: string) => `npm 包名 ${name} 校验不通过，请重试`,
  selectProjectType: '请选择项目类型',
  webLibrary: '前端类库',
  nodeModule: 'Node 模块',
  reactComponent: 'React 组件',
  raxComponent: 'Rax 组件',
};
