[package]
name = "pkg_loader_alias"
version = "0.1.0"
edition = "2021"
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pkg_loader = { workspace = true }
async-trait = { workspace = true }
