/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RawTransformOptions {
  srcDir: string
  inputFiles: Array<string>
  outDir: string
  target: string
  module: 'es6' | 'commonjs'
}
export function transform(rawOptions: RawTransformOptions): Promise<void>
