/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TaskConfig {
  rootDir: string
  entryDir: string
  outputDir: string
  mode: string
  taskName: string
  transformExcludes?: Array<string>
  transforms?: Array<(...args: any[]) => any>
}
export function doTransform(taskConfig: TaskConfig): void
export function callThreadsafeFunction(callback: (...args: any[]) => any): void
export function sum(a: number, b: number): number
