/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformInput {
  id: string
  code: string
  map?: string
}
export interface TransformResult {
  code: string
  map?: string
}
export interface TaskConfig {
  rootDir: string
  entryDir: string
  outputDir: string
  mode: string
  taskName: string
  transformExcludes?: Array<string>
  transforms?: Array<(err: Error | null, value: TransformInput) => any>
}
export function doTransform(taskConfig: TaskConfig): Promise<void>
export function transform(id: string, code: string, map: string | undefined | null, loader: (err: Error | null, value: TransformInput) => any): Promise<TransformResult>
