module.exports = {
  configSidebar: [
    { type: 'doc', id: 'config/index' },
    { type: 'doc', id: 'config/entry' },
    { type: 'doc', id: 'config/alias' },
    { type: 'doc', id: 'config/define' },
    { type: 'doc', id: 'config/source-maps' },
    { type: 'doc', id: 'config/jsx-runtime' },
    { type: 'doc', id: 'config/plugins' },
    { type: 'doc', id: 'config/helpers' },
    { type: 'doc', id: 'config/declaration' },
    { type: 'doc', id: 'config/server' },
    { type: 'doc', id: 'config/transform' },
    { type: 'doc', id: 'config/bundle' },
    { type: 'doc', id: 'config/pkgs' },
  ],

  tutorialSidebar: [
    { type: 'doc', id: 'index' },
    { type: 'doc', id: 'quick-start' },
    {
      type: 'category',
      label: '场景',
      collapsed: false,
      items: [
        { type: 'doc', id: 'guide/scenario/react' },
        { type: 'doc', id: 'guide/scenario/node' },
        { type: 'doc', id: 'guide/scenario/library' },
      ],
    },
    {
      type: 'category',
      label: '基础',
      collapsed: false,
      items: [
        { type: 'doc', id: 'guide/configure' },
        { type: 'doc', id: 'guide/build-modes' },
        { type: 'doc', id: 'guide/build' },
      ],
    },
    {
      type: 'category',
      label: '进阶',
      collapsed: false,
      items: [
        { type: 'doc', id: 'guide/typescript' },
        { type: 'doc', id: 'guide/css' },
        { type: 'doc', id: 'guide/engine' },
        { type: 'doc', id: 'guide/mf' },
        { type: 'doc', id: 'guide/jsx-plus' },
        { type: 'doc', id: 'guide/monorepo' },
        { type: 'doc', id: 'guide/test' },
        { type: 'doc', id: 'guide/server' },
        { type: 'doc', id: 'guide/preview' },
      ],
    },
    {
      type: 'category',
      label: '插件',
      collapsed: false,
      items: [
        { type: 'doc', id: 'plugin/usage' },
        { type: 'doc', id: 'plugin/development' },
      ],
    },
    { type: 'doc', id: 'cli' },
    { type: 'doc', id: 'faq' },
    { type: 'doc', id: 'ai' },
    {
      type: 'category',
      label: '迁移',
      collapsed: false,
      items: [{ type: 'doc', id: 'migration/v1-to-v2' }],
    },
  ],
};
