name: ci

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Set branch name
        uses: actions/checkout@v3

      - name: Echo branch name
        run: echo ${BRANCH_NAME}

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm run setup
      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run coverage

      - run: pnpm run build:doc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        if: github.ref == 'refs/heads/main'
        with:
          BRANCH: gh-pages
          FOLDER: website/build
