name: Pull Request Check
on: [pull_request]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup
        run: pnpm run setup

      - run: pnpx pkg-pr-new publish './packages/*' --template './examples/*'
